title: "Yurong Chen"
tagline: "Ph.D. Student at Hunan University"
description: >
  Hyperspectral Imaging · Machine Learning · Computational Imaging

remote_theme: pages-themes/minimal@v0.2.0

lang: "en"
url: "https://YurongChen1998.github.io"
baseurl: ""

# Author and contact info
author:
  name: "Yurong Chen"
  email: "chenyurong1998@outlook.com"

# Social links
social:
  links:
    - "https://github.com/YurongChen1998"
    - "https://scholar.google.com/citations?user=-HuRr-EAAAAJ"
    - "https://www.bilibili.com/video/BV1HJ4m1P7NH/"

# Theme settings
logo: /img/yurong_hiking.jpg

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
