theme: jekyll-theme-minimal
logo: img/yurong.png
description: Ph.D Student \ IEEE Member \ CSIG Student Member
title: Yurong's Homepage

#########
plugins:
  - jekyll-relative-links
  - jekyll-include-cache
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
