theme: jekyll-theme-minimal
title: Yurong's Homepage
title-img: "../img/yurong.png"

# --- List of links in the navigation bar --- #

nav:
  - About Me: "aboutme"
  - Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  - Author's home: "https://deanattali.com"
