theme: jekyll-theme-minimal
title: Yurong's Homepage
title-img: "./yurong.jpeg"
round-title-img: true

# --- List of links in the navigation bar --- #

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
